name    'saz-pureftpd'
version '1.0.2'
source 'UNKNOWN'
author 'saz'
license 'UNKNOWN'
summary 'UNKNOWN'
description 'Module for configuring pure-ftpd via puppet'
project_page 'https://github.com/saz/puppet-pureftpd'
